CREATE TABLE dbo.tblProductGrade (
	ProductGradeId BIGINT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	Grade SMALLINT DEFAULT 0 CONSTRAINT CK_ProductGrade_Grade CHECK (Grade >= 0 AND Grade <= 5),
	ProductId UNIQUEIDENTIFIER NOT NULL,
	UserId INT NOT NULL,

	CONSTRAINT FK_PRODUCT_PRODUCTGRADE FOREIGN KEY(ProductId) REFERENCES dbo.tblProducts(ProductId),
	CONSTRAINT FK_USER_PRODUCTGRADE FOREIGN KEY(UserId) REFERENCES dbo.tblUsers(UserId)
);
